{% set name = "whyqd" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whyqd-{{ version }}.tar.gz
  sha256: 9d2f51166ac75b0aaa1caf3a438d91057c377c95e6336c9ed3306e487c72f653

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - numpy >=1.21.1,<2.0.0
    - openpyxl >=3.0.7,<4.0.0
    - pandas >=1.5.2,<2.0.0
    - xlrd >=2.0.1,<3.0.0
    - pydantic >=1.8.2,<2.0.0
    - tabulate >=0.8.9,<0.9.0
    - ray-core >=2.2.0,<3.0.0
    - modin >=0.20.1,<0.21.0
    - randomname >=0.2.1,<0.3.0
    - pyarrow >=11.0.0,<12.0.0
    - setuptools >=67.7.2
    - python-dotenv >=1.0.0,<2.0.0

test:
  imports:
    - whyqd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://whyqd.com
  doc_url: https://whyqd.readthedocs.io/
  dev_url: https://github.com/whythawk/whyqd
  summary: A curatorial toolkit intended to produce well-structured and predictable data for research analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
