{% set name = "whyqd" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/whyqd-{{ version }}.tar.gz
  sha256: 9653140ff88ffdc7f9b63258aa57b3ea5475ae8c99443a9a6fa02948f6401f38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.21.1
    - openpyxl >=3.0.7
    - pandas >=1.5.2
    - xlrd >=2.0.1
    - pydantic >=1.8.2
    - tabulate >=0.8.9
    - ray-core >=2.2.0
    - modin >=0.25.1
    - randomname >=0.2.1
    - pyarrow >=11.0.0
    - setuptools >=67.7.2
    - python-dotenv >=1.0.0
    - grpcio >=1.59.3,<2.0.0
    - pydantic-settings >=2.8.1,<3.0.0

test:
  imports:
    - whyqd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://whyqd.com
  doc_url: https://whyqd.readthedocs.io/
  dev_url: https://github.com/whythawk/whyqd
  summary: A curatorial toolkit intended to produce well-structured and predictable data for research analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
